version: 2.1

jobs:

  compile:

   docker:

      - image: fadlyas/kernel_dockerfile:latest

   steps:

      - run:

          command: |

           apt update && apt install -y default-jre nano flex

           git config --global user.name "Popo21xyz"

           git config --global user.email "popo21xyz@gmail.com"
           
           git remote add origin https://github.com/Popo21xyz/Ughtea_msm8953.git



           git pull origin master
           
           git push origin 

workflows:

  version: 2.1

  cooking:

    jobs:

      - compile
