version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: git clone --bare "https://github.com/SebaUbuntu/android_kernel_xiaomi_msm8953.git" --branch "lineage-18.0"
