version: 2.1

jobs:

  compile:

   docker:

      - image: fadlyas/kernel_dockerfile:latest

   steps:

      - run:

          command: |

           apt update && apt install -y default-jre nano flex

           git config --global user.name "Popo21xyz"

           git config --global user.email "popo21xyz@gmail.com"
           
           cd anroid_kernel_xiaomi_msm8953

           git pull
           
           git push

workflows:

  version: 2.1

  cooking:

    jobs:

      - compile
